### ISSUE TITLE
Activity table cells uneditable.

### ISSUE THREAD

**Issue by MarinKacaj** [Krisli/project-manager#42]
Bug or feature?

**Comment by Krisli** [comment]
Uneditable only if activity is parent, otherwise it's a bug

**Comment by MarinKacaj** [comment]
It's probably because it's a parent activity.However I cannot confirm: Sub activity cannot be added. The budget is required to add it, but there is no budget field in the modal form.


    On Wednesday, February 3, 2016 2:01 PM, Krisli <notifications@github.com> wrote:
 

 Uneditable only if activity is parent, otherwise it's a bug—

**Comment by Krisli** [comment]
The budget was supposed to be automatically generated as planned amount * price per unit. It was removed at the last minute, but the feature to calculate it was not implemented. As a temporary fix, just add back the budget input on the fxml file.

**Comment by MarinKacaj** [comment]
OK, thank you for the timely response and for the fix.
Anyway, if a long-term solution is required, please let me know.
